name: linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [3.9, 3.10]

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: upgrade pip
        run: python -m pip install --upgrade pip

      - name: install lint & format tools
        run: |
          python -m pip install flake8 autopep8

      - name: auto-fix style issues with autopep8
        # autopep8 will edit files in-place on the runner to fix common issues (e.g. blank lines)
        run: |
          autopep8 --in-place --aggressive --aggressive app.py || true

      - name: run flake8
        run: flake8 app.py
